Added etcd storage
artipie/asto pull request #306
Opened 2021-04-20 13:59 UTC by g4s8

For #305 - introduced etcd storage, added integration test
using junit extension.

2021-04-20 14:28 UTC, olenagerasimova requested changes
@g4s8 thanks, please, check my comments

2021-04-20 14:28 UTC, olenagerasimova commented on README.md
> + - `Key` - storage keys, could be conferted to strings
@g4s8 seems like typo `conferted` -> `converted`

2021-04-20 14:28 UTC, olenagerasimova commented on src/main/java/com/artipie/asto/etcd/EtcdStorage.java
> +            .to(SingleInterop.get())
@g4s8 you can simply use `PublisherAs()` here to read all bytes from `content`

2021-04-20 14:28 UTC, olenagerasimova commented on src/main/java/com/artipie/asto/etcd/EtcdStorage.java
> +        return this.client.getKVClient().delete(keyToSeq(key)).thenApply(ignore -> (Void) null);
@g4s8 hm, will this method fail if key does not exist? It should according to `Storage` contract

2021-04-21 09:19 UTC, olenagerasimova approved these changes
@g4s8 thanks

2021-04-21 09:44 UTC, merged

2021-04-21 09:44 UTC, g4s8 commented
@olenagerasimova thanks

2021-04-21 09:44 UTC, 0pdd commented
@g4s8 2 puzzles [#309](https://github.com/artipie/asto/issues/309), [#310](https://github.com/artipie/asto/issues/310) are still not solved.

2021-11-29 13:06 UTC, 0pdd commented
@g4s8 2 puzzles [#310](https://github.com/artipie/asto/issues/310), [#384](https://github.com/artipie/asto/issues/384) are still not solved; solved: [#309](https://github.com/artipie/asto/issues/309).

2021-12-07 14:18 UTC, 0pdd commented
@g4s8 the puzzle [#384](https://github.com/artipie/asto/issues/384) is still not solved; solved: [#309](https://github.com/artipie/asto/issues/309), [#310](https://github.com/artipie/asto/issues/310).