Added artipie base exception classes
artipie/asto pull request #313
Opened 2021-05-19 09:58 UTC by g4s8

Fixes #311 - added `ArtipieException` base class and
`ArtipieIOException` for `asto` module, replaced
all API-related exceptions in storage implementations and
supplementary classes with these exceptions. Updated tests
to expect correct exception types on failure.

2021-05-19 11:16 UTC, olenagerasimova requested changes
@g4s8 thanks, two comments, take a look please

2021-05-19 11:16 UTC, olenagerasimova commented on src/main/java/com/artipie/ArtipieException.java
> + *  practice to not it via {@code throws} tag in JavaDocs.
@g4s8 hm, seems like there is some mistake in the sentence, I do not understand the meaning of the second part

2021-05-19 11:16 UTC, olenagerasimova commented on src/main/java/com/artipie/asto/ArtipieIOException.java
> +public class ArtipieIOException extends ArtipieException {
@g4s8 I'd suggest to add ctor from string and `Throwable`

2021-05-19 11:28 UTC, g4s8 commented
> @g4s8 thanks, two comments, take a look please

@olenagerasimova thanks, fixed

2021-05-19 11:38 UTC, olenagerasimova commented
@g4s8 hm, do not see any changes

2021-05-19 12:19 UTC, g4s8 commented
> @g4s8 hm, do not see any changes

@olenagerasimova sorry, push failed, please see https://github.com/artipie/asto/pull/313/commits/69ed32d6f0f8a1bf2e312ef880adb61f834a5dfe

2021-05-19 12:21 UTC, olenagerasimova approved these changes
@g4s8 thanks

2021-05-19 13:52 UTC, merged

2021-05-26 08:36 UTC, g4s8 commented
@rultor stop

2021-05-26 08:37 UTC, rultor commented
> @rultor stop

@g4s8 Sorry, I failed to stop the previous command, however it has the following result: Oops, I failed. You can see the full log [here](https://www.rultor.com/t/24553-848581579) (spent 28s)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 6378
+ echo '1.69.1 839260fab'
1.69.1 839260fab
+ date
Wed May 26 10:37:41 CEST 2021
+ uptime
 10:37:41 up 240 days, 18:43,  0 users,  load average: 0.22, 0.42, 0.22
+ ff=default
+ image=g4s8/rultor:alpine3.10
+ rebase=false
+ squash=false
+ author=g4s8
+ vars=('--env=scripts=( '\''export '\''\'\'''\''author=g4s8'\''\'\'''\'''\'' '\'';'\'' '\''export LC_ALL=en_US.UTF-8'\'' '\'';'\'' '\''export LANG=en_US.UTF-8'\'' '\'';'\'' '\''export LANGUAGE=en_US.UTF-8'\'' '\'';'\'' )' '--env=author=g4s8')
+ scripts=('export '\''author=g4s8'\''' ';' 'export LC_ALL=en_US.UTF-8' ';' 'export LANG=en_US.UTF-8' ';' 'export LANGUAGE=en_US.UTF-8' ';')
+ directory=
+ container=artipie_asto_313
+ as_root=false
+ mkdir -p /home/rultor/.ssh
+ echo -e 'Host github.com\n\tStrictHostKeyChecking no\n'
+ chmod 600 /home/rultor/.ssh/config
+ git clone '' repo
fatal: repository '' does not exist
'cid' file is absent, Docker container is not running
'cid' file is absent, container wasn't started correctly
```