test: cover BlockingStorage and RxStorageWrapper
artipie/asto pull request #386
Opened 2021-12-20 12:18 UTC by baudoliver7

- test remaining functions of `BlockingStorage`
- test all functions of RxStorageWrapper

Ref: #55, #383
Close: #55

2021-12-20 12:27 UTC, baudoliver7 commented
@artipie/maintainers ready to be reviewed :)

2021-12-22 18:05 UTC, genryxy requested changes
@baudoliver7 thanks, one suggestion

2021-12-22 18:49 UTC, baudoliver7 commented on src/test/java/com/artipie/asto/blocking/BlockingStorageTest.java
> +        );
Ok

2021-12-22 19:06 UTC, genryxy approved these changes
@baudoliver7 thanks, looks good to me
@g4s8 please check

2021-12-23 16:18 UTC, baudoliver7 commented
@g4s8 how about this ?

2021-12-24 07:09 UTC, merged