fix: added parts information to `CompleteMultipartUploadRequest`
artipie/asto pull request #425
Opened 2022-05-20 14:34 UTC by dgarus

closes: #421

- created `Splitting` class to split `ByteBuffer` at parts
- created tests to check `Splitting` implementation
- added filling of `multipartUpload` field of `CompleteMultipartUploadRequest`

2022-05-20 14:40 UTC, dgarus commented
@olenagerasimova 
Could you please have a look?

2022-05-23 06:39 UTC, olenagerasimova requested changes
@dgarus thanks, check my comments please

2022-05-23 06:39 UTC, olenagerasimova commented on src/main/java/com/artipie/asto/Splitting.java
> +            final List<ByteBuffer> parts = new ArrayList<>(16);
why 16? It seems, like we can calculate the size by dividing `remaining` into `this.size`

2022-05-23 06:39 UTC, olenagerasimova commented on src/main/java/com/artipie/asto/s3/MultipartUpload.java
> +                    ).<Void>thenApply(
It would be better to use `thenAccept` here instead of  `thenApply` as `thenAccept` returns void itself

2022-05-23 06:39 UTC, olenagerasimova commented on src/main/java/com/artipie/asto/s3/MultipartUpload.java
> +            .toCompletableFuture()
This line is not required, we already switched to completables, `thenCompose` can be called without calling `toCompletableFuture()`

2022-05-23 09:27 UTC, olenagerasimova approved these changes
@dgarus thanks, looks good

2022-05-23 09:27 UTC, merged